const KeyAliasMap = {
  'tab': 'Tab',
  'del': 'Backspace',
  'backspace': 'Backspace',
  'capslock': 'CapsLock',
  'enter': 'Enter',
  'return': 'Enter',
  'shift': 'Shift',
  'command': 'Meta',
  'meta': 'Meta',
  'option': 'Alt',
  'alt': 'Alt',
  'left': 'ArrowLeft',
  'right': 'ArrowRight',
  'up': 'ArrowUp',
  'down': 'ArrowDown',
  'ins': 'Insert',
  'ctrl': 'Control',
  'pageup': 'PageUp',
  'pagedown': 'PageDown',
  'end': 'End',
  'home': 'Home',
  'space': ' ',
  'escape': 'Escape',
  'esc': 'Escape',
};

export default KeyAliasMap;
