#!/bin/bash -e

# ====================================================================================
# Replaces previous UMD build with code transpiled (using Babel and Webpack) from
# the source files in /lib. A minified version of the UMD module is also included.
# ====================================================================================

# Remove old build files
rm -rf build/global
# Retrieve name of package from package.json
name=$(node -p "require('./package').name")
# Use webpack (with config from webpack.config.js) to package up UMD module
NODE_ENV=production webpack lib/index.js "build/global/${name}.js"
# Create a minified version of the UMD module
NODE_ENV=production COMPRESS=1 webpack lib/index.js "build/global/${name}.min.js"
# Output location and size of minified version
echo "gzipped, the global build is `gzip -c build/global/${name}.min.js | wc -c` bytes"
