#!/bin/bash -e

rm -rf build/npm
./node_modules/.bin/babel -d build/npm/lib ./lib
cp README.md build/npm/
cp index.d.ts build/npm/
find -X build/npm/lib -type d -name __tests__ | xargs rm -rf
node -p "p=require(\"./package.json\");p.main=\"lib\";p.scripts=p.devDependencies=undefined;JSON.stringify(p,null,2)" > build/npm/package.json
